-- Migration user
CREATE ROLE cl_migrate WITH LOGIN PASSWORD 'cl_migrate' NOSUPERUSER NOCREATEDB NOCREATEROLE;

GRANT CONNECT, CREATE ON DATABASE testdb TO cl_migrate;
GRANT CREATE ON SCHEMA public TO cl_migrate;

-- API role
CREATE ROLE cl_rw WITH NOSUPERUSER NOCREATEDB NOCREATEROLE;

-- API user
CREATE ROLE cl_api WITH LOGIN PASSWORD 'cl_api';
GRANT cl_rw TO cl_api WITH SET FALSE;

-- Auth user
CREATE ROLE cl_auth WITH LOGIN PASSWORD 'cl_auth';
