name: Build and test

on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/build-and-test-dev.yaml'
      - 'src/**'
      - 'Cargo.lock'

env:
  DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Build dev binary
      run: cargo build

    - name: Run clippy
      run: cargo clippy

    - name: Connect to Tailscale
      uses: tailscale/github-action@v4
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci

    - name: Run tests
      run: cargo test -- --test-threads=1 --verbose
