name: Build and deploy to web server

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-and-deploy-main.yaml'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Run tests
      run: cargo test --bin clearlist-api --release --verbose

    - name: Build release
      run: cargo build --bin clearlist-api --release

    - name: Connect to Tailscale
      uses: tailscale/github-action@v4
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci

    - name: Upload binary to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: ./target/release/clearlist-api
        strip_components: 3
        target: /tmp/clearlist-api/

    - name: Deploy binary to working path and restart service
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          sudo -n systemctl stop clearlist-api.service
          cp /tmp/clearlist-api/clearlist-api ${{ secrets.DEPLOY_PATH }}
          sudo -n systemctl start clearlist-api.service
