name: Build and test

on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/build-and-test-dev.yaml'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  SQLX_OFFLINE: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Build release
      run: cargo build --bin clearlist-api --release

    - name: Run tests
      run: cargo test --bin clearlist-api --release --verbose
