name: Build and deploy to web server

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-and-deploy.yaml'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Run tests
      run: cargo test --bin clearlist-api --verbose

    - name: Build release
      run: cargo build --bin clearlist-api --release

    - name: Upload binary
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USER }}
        proxy_key: ${{ secrets.PROXY_KEY }}
        source: target/release/todo-api
        target: /tmp/clearlist-api/
        strip_components: 2

    - name: Setup server binary and restart
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USER }}
        proxy_key: ${{ secrets.PROXY_KEY }}
        script: |
          sudo -n systemctl stop clearlist-api.service
          cp /tmp/clearlist-api/clearlist-api ${{ secrets.DEPLOY_PATH }}
          sudo -n systemctl start clearlist-api.service
